### ISSUE TITLE
Change compileSdkVersion and targetSdkVersion from "android-R", "R" to 30

### ISSUE THREAD

**Issue by yanzm** [googlecodelabs/while-in-use-location#11]
At step 5. Support Android 11 (https://codelabs.developers.google.com/codelabs/while-in-use-location/index.html?index=..%2F..index#4),
requested changes are compileSdkVersion to "android-R", targetSdkVersion to "R", but these should be 30 like this.

```gradle
android {
   // TODO: Step 2.1, Target Android 11.
   compileSdkVersion 30
   defaultConfig {
       applicationId "com.example.android.whileinuselocation"
       minSdkVersion 26
       targetSdkVersion 30
       versionCode 1
       versionName "1.0"
   }
...
}
```

**Comment by codingjeremy** [comment]
I just put in a PR to fix. I will update docs too.
