### ISSUE TITLE
Source code doesn't correspond do codelab exercises

### ISSUE THREAD

**Issue by solikhver** [googlecodelabs/while-in-use-location#13]
I have tried to follow instructions in [Google Dev Codelab](https://google.dev/codelabs/while-in-use-location), but have found that source code doesn't correspond to codelab exercises starting from _TODO: 2.2_ 
It seems that source code was updated 09.04.2020, but codelab wasn't.

**Comment by NoemiOro** [comment]
Hi, I think I have found the codelab which corresponds to this code: [https://codelabs.developers.google.com/codelabs/while-in-use-location/index.html?index=..%2F..ads19#0]

**Comment by vDuh** [comment]
Hi, this bug has not been fixed yet.

**Comment by codingjeremy** [comment]
It follows this codelab:
https://developers.google.com/codelabs/while-in-use-location

I put in a PR to the README to fix.
