### ISSUE TITLE
Codelab needs to be updated

### ISSUE THREAD

**Issue by Pluu** [googlecodelabs/while-in-use-location#8]
Codelab Step needs to be updated.
Screenshot and description of `base` and `completed` module are past version.

- Change Version :  https://github.com/googlecodelabs/while-in-use-location/pull/6/commits/2f6b5d40c7a77617995d8954c965b240ed67eb91

| Codelab | Github |
| :--: | :--: |
| <img src="https://user-images.githubusercontent.com/1534926/81474586-80397480-9241-11ea-9b5d-ab989dfa813b.png" width="400" /> | <img src="https://user-images.githubusercontent.com/1534926/81474596-8cbdcd00-9241-11ea-98ea-07b37ad67ba1.png" width="400" /> |

**Comment by codingjeremy** [comment]
Thanks for the catch! 

It should be resolved now. There was a short period where I hadn't updated the codelab and you caught it! :)

If you still see the issue, please re-open and link me to the step and I will fix ASAP.
